name: CI

on: 
  push:
    branches:
      - workflows-test

jobs:
  build:

    runs-on: macOS-10.14
    
    steps:
    - uses: actions/checkout@workflows-test
    - name: Start xcodebuild test
      run: |
        xcodebuild test -project TodoSampleApp.xcodeproj -scheme TodoSampleApp -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6,OS=12.2"
