name: CI

on: 
  push:
    branches:
      - workflows-test

jobs:
  build:

    runs-on: macOS-10.14
    
    steps:
    - uses: actions/checkout@master
    - name: showsdks
      run: |
        xcodebuild -showsdks
