name: CI

on: 
  push:
    branches:
      - workflows-test

jobs:
  build:

    runs-on: macOS-10.14
    
    steps:
    - uses: actions/checkout@master
    - name: Xcode 11 macOS
      run: |
        ls -al /Applications/Xcode_11.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
    - name: Xcode 9.4 macOS
      run: |
        ls -al /Applications/Xcode_9.4.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
    