name: CI

on: 
  push:
    branches:
      - workflows-test

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Start xcodebuild test
      run: |
        xcodebuild test -project TodoSampleApp.xcodeproj -scheme TodoSampleApp -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.1'